spring:
  application:
    name: web-honeypot
  data:
    mongodb:
      database: honeypot
      host: localhost
      port: 27017
      auto-index-creation: true
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  security:
    user:
      name: admin
      password: ${ADMIN_PASSWORD:admin123}
      roles: ADMIN

server:
  port: 9999
  servlet:
    context-path: /
  tomcat:
    max-threads: 200
    min-spare-threads: 10
    max-connections: 10000

honeypot:
  virtual-environment:
    os: Ubuntu
    version: 20.04
    max-processes: 100
    max-file-size: 10MB
    allowed-commands:
      - ls
      - cat
      - ps
      - pwd
  security:
    rate-limit:
      enabled: true
      max-requests: 100
      window-size: 60
      strict-mode-threshold: 1000
    alert:
      enabled: true
      email: admin@example.com
      webhook: http://alert-service/webhook
      threshold:
        attack-count: 100
        ip-block: 50
    blacklist:
      enabled: true
      max-size: 10000
      expire-hours: 24
  monitoring:
    enabled: true
    interval: 60000
    metrics:
      enabled: true
    logging:
      path: logs/honeypot.log
      level: INFO
      max-size: 100MB
      max-history: 30

logging:
  level:
    root: INFO
    com.example.web_honeypot: DEBUG
  file:
    name: logs/honeypot.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized 